name: PlayerStats
version: '${project.version}'
main: me.skippysunday.playerstats.PlayerStats
api-version: '1.20'

commands:
  where:
    description: Get location information about a player

  health:
    description: Get health related info

  inv:
    description: See contents of Player inventories

  potions:
    description: See all potion effects on a player

  permissions:
    description: View permissions of a player

permissions:
  playerstats.*:
    description: All encompassing permission for all PS commands
    children:
      playerstats.location: true
      playerstats.health: true
      playerstats.inv: true
      playerstats.potions: true
      playerstats.permissions: true

  playerstats.where:
    description: Alllows usage of /where command

  playerstats.health:
    description: Allows use of /health command

  playerstats.inv:
    description: Allows use of /inv command

  playerstats.potions:
    description: Allows use of /potions command

  playerstats.permissions:
    description: Allows use of /permissions command
